// Generated by CoffeeScript 1.7.1

/*

	Author: James Forbes
	Date: 2014-18-05
	Version: 0.01
	Licence: MIT
 */

(function() {
  (function() {
    var attributes, headings, i, isObject, tag, tagCreator, tags, _i, _len, _results;
    isObject = function(obj) {
      return obj === Object(obj);
    };
    tagCreator = function(tag) {
      return function(attr, content) {
        if (arguments.length === 1 && !isObject(attr)) {
          content = attr;
        }
        content = content || '';
        content = content.join && content.join('') || content;
        return "<" + tag + (attributes(attr)) + ">" + content + "</" + tag + ">";
      };
    };
    attributes = function(attr) {
      var key, result, value;
      if (isObject(attr)) {
        result = ((function() {
          var _results;
          _results = [];
          for (key in attr) {
            value = attr[key];
            _results.push("" + key + "='" + value + "' ");
          }
          return _results;
        })()).join('');
        return result = result.length > 0 && ' ' + result || result;
      } else {
        return '';
      }
    };
    headings = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 6; i = ++_i) {
        _results.push("h" + i);
      }
      return _results;
    })();
    tags = ['div', 'img', 'p', 'a', 'i', 'b', 'script', 'code', 'pre', 'ul', 'ol', 'li', 'canvas', 'table'].concat(headings);
    _results = [];
    for (_i = 0, _len = tags.length; _i < _len; _i++) {
      tag = tags[_i];
      _results.push(window[tag] = tagCreator(tag));
    }
    return _results;
  })();

}).call(this);
